# Generated by Django 4.1.3 on 2023-03-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0002_libros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libro',
        ),
    ]
