# Generated by Django 4.1.6 on 2023-03-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0002_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='isbn13',
            new_name='isbn',
        ),
    ]
