# Generated by Django 4.1.3 on 2023-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0003_rename_libros_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn13',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
