# Generated by Django 4.1.6 on 2023-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0003_rename_isbn13_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.CharField(max_length=15),
        ),
    ]
