# Generated by Django 4.1.3 on 2023-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0004_alter_libro_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn13',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
