# Generated by Django 4.1.3 on 2023-03-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0004_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('nota_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_nota', models.CharField(max_length=100)),
                ('contenido_nota', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
