# Generated by Django 4.1.3 on 2023-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0005_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='editorial',
            new_name='editorial234',
        ),
    ]
