# Generated by Django 4.1.3 on 2023-03-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0006_rename_editorial_libro_editorial234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='editorial234',
            new_name='editorial',
        ),
    ]
