# Generated by Django 4.1.3 on 2023-03-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0007_rename_editorial234_libro_editorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='correo69',
        ),
    ]
