# Generated by Django 4.1.3 on 2023-03-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0008_rename_correo_usuario_correo69'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo69',
            new_name='correo',
        ),
    ]
