# Generated by Django 4.1.3 on 2023-03-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0009_rename_correo69_usuario_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
