# Generated by Django 4.1.6 on 2023-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0010_rename_notas_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('reto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('tituloReto', models.CharField(max_length=20)),
                ('estadoReto', models.BooleanField()),
            ],
        ),
    ]
