# Generated by Django 4.1.6 on 2023-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0011_reto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('recordatorio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=20)),
                ('hora', models.DateTimeField(max_length=10)),
                ('metaDiaria', models.IntegerField()),
            ],
        ),
    ]
