# Generated by Django 4.1.6 on 2023-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0012_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='hora',
            field=models.CharField(max_length=10),
        ),
    ]
