# Generated by Django 4.1.3 on 2023-04-23 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Omni', '0013_alter_recordatorio_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='id_UsuarioNota',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
