# Generated by Django 4.1.3 on 2023-04-23 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Omni', '0014_nota_id_usuarionota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lib_User',
            fields=[
                ('libuser_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omni.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
