# Generated by Django 4.1.3 on 2023-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0015_lib_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib_user',
            name='libuser_ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
