# Generated by Django 4.1.6 on 2023-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0016_alter_lib_user_libuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib_user',
            name='pagleidas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
