# Generated by Django 4.1.6 on 2023-04-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0017_lib_user_pagleidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='calificacion_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='libro',
            name='calificacion_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='libro',
            name='num_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
