# Generated by Django 4.1.6 on 2023-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0018_libro_calificacion_promedio_libro_calificacion_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
