# Generated by Django 4.1.3 on 2023-05-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0019_libro_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contenido_review', models.TextField()),
                ('fecha_review', models.DateTimeField(auto_now_add=True)),
                ('libuser_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omni.lib_user')),
            ],
        ),
    ]
