# Generated by Django 4.1.6 on 2023-05-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omni', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib_user',
            name='tiempoLeido',
            field=models.IntegerField(default=0),
        ),
    ]
